# Generated by Django 3.2.21 on 2023-10-01 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url_da_capa', models.URLField(default='https://www.intercabos.com.br/wp-content/uploads/produto-sem-imagem.jpg')),
                ('diretor', models.CharField(default='Não informado', max_length=200)),
                ('faixa_etaria', models.IntegerField(default=0)),
                ('data_lancamento', models.DateField(default=django.utils.timezone.now)),
                ('resumo', models.TextField()),
                ('nota', models.FloatField(default=0)),
            ],
        ),
    ]
